#!/usr/bin/env bash
# Removes every row generated by loadtest-generate.sh (tagged {"_lt": true}), leaving the normal
# seed/dev data untouched.
set -euo pipefail
cd "$(dirname "$0")/../.."

CONTAINER=platform_postgres
DB=platform
DBUSER=postgres

docker exec -i "$CONTAINER" psql -v ON_ERROR_STOP=1 -U "$DBUSER" -d "$DB" <<'SQL'
\timing on
DELETE FROM edges WHERE properties->>'_lt' = 'true';
DELETE FROM objects WHERE properties->>'_lt' = 'true';
ANALYZE objects;
ANALYZE edges;
SQL
